version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  browser-tools: circleci/browser-tools@1.0.1

jobs:
  lintering:
    docker:
      - image: cimg/ruby:3.0.3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: lefthook
          command: bundle exec lefthook run pre-commit

  testing:
    docker:
      - image: cimg/ruby:3.0.3
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: codica_med_test
          POSTGRES_PASSWORD: postgres
    environment:
      DATABASE_URL: postgresql://postgres@localhost
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: run specs
          command: bundle exec rspec

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lintering
      - testing:
          requires:
            - lintering
