default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  url: <%= ENV['DATABASE_URL'] %>


development:
  <<: *default
  database: codica_med_development

test:
  <<: *default
  database: codica_med_test

production:
  <<: *default
  database: codica_med_production
